### ISSUE TITLE
periodic  Todoist API: HTTPSConnectionPool(host='api.todoist.com', port=443): Read timed out. (read timeout=None)

### ISSUE THREAD

**Issue by bcohen44** [Hoffelhas/automation-todoist#18]
See this HTTP timeout randomly when letting autodoist run.  Do you think I solve this by specifying a longer then default (5s) interval?

```022-01-21 13:55:24 INFO     No changes in queue, skipping sync.
2022-01-21 13:55:29 INFO     No changes in queue, skipping sync.
2022-01-21 13:55:34 INFO     No changes in queue, skipping sync.
2022-01-21 13:55:57 ERROR    Error trying to sync with Todoist API: HTTPSConnectionPool(host='api.todoist.com', port=443): Read timed out. (read timeout=None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 353, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.todoist.com', port=443): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bcohen/autodoist/autodoist.py", line 33, in sync
    api.sync()
  File "/usr/local/lib/python3.9/site-packages/todoist/api.py", line 358, in sync
    response = self._post("sync", data=post_data)
  File "/usr/local/lib/python3.9/site-packages/todoist/api.py", line 331, in _post
    response = self.session.post(url + call, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.todoist.com', port=443): Read timed out. (read timeout=None)```

**Comment by Hoffelhas** [comment]
Hi there, sorry it took a while for me to get back at you! Since I'm currently working on a big overhaul, and also Todoist's API has completely changed, I'm closing this topic for now. If a similar issue is experienced in the future, feel free to open a new ticket!

**Comment by bcohen44** [comment]
Ok.
just came back to Todoist and autodoist, and noticed that "next: action auto labeling is no longer working, like at all.
