### ISSUE TITLE
Label formatting and "-hf" switch

### ISSUE THREAD

**Issue by moorsey** [Hoffelhas/automation-todoist#6]
Hi there,

Been testing this in docker and got it working OK, will post the instructions for other users once I have things fully working, but just wanted to check a few things

With the "-l" switch, should the label be with an "@" prefix or not?  I have tried both, but each time get an error saying the label does not exist.  As I am not running interactively, I cannot say "y" to this, but just made sure the label already existing.  Autodoist seems to think it isn't though, saying `Label ' @next' doesn't exist in your Todoist`

Note the space before the label name, which could be the issue,  My command is:

`python autodoist.py -a API_KEY_HERE -r 2 -l next --hf 8`

Full error output:

```
   Next action labelling mode: Enabled

   Regenerate sub-tasks mode: Enabled

   Shifted end-of-day mode: Disabled

2021-01-31 15:53:07 INFO    

Label ' @next' doesn't exist in your Todoist

Traceback (most recent call last):

  File "/app/autodoist.py", line 1005, in <module>

    main()

  File "/app/autodoist.py", line 959, in main

    api, label_id, regen_labels_id = initialise(args)

  File "/app/autodoist.py", line 166, in initialise

    label_id = verify_label_existance(args, api, args.label, 1)

  File "/app/autodoist.py", line 91, in verify_label_existance

    response = query_yes_no(

  File "/app/autodoist.py", line 65, in query_yes_no

    choice = input().lower()

EOFError: EOF when reading a line

Do you want to automatically create this label? [Y/n] 
```

My next issue is with running the "-hf" switch, which gives me:

```
autodoist.py: error: argument -h/--help: ignored explicit argument 'f 8'


usage: autodoist.py [-h] [-a API_KEY] [-l LABEL] [-r [REGENERATION]] [-e END] [-d DELAY] [-pp PP_SUFFIX] [-ss SS_SUFFIX]


                    [-ps PS_SUFFIX] [-sp SP_SUFFIX] [-df DATEFORMAT] [-hf HIDE_FUTURE] [--onetime] [--nocache] [--debug]


                    [--inbox {parallel,sequential}]
```

Also tried with "--hf" as in the example, but get `autodoist.py: error: unrecognized arguments: --hf 8`

If it is just me getting this, then it could be the docker environment causing the issues, in which case I'll go away and play some more!

Many thanks

**Comment by moorsey** [comment]
Ignore, solved this, switches have to be added without spaces, so this works:

`autodoist.py -a=API_KEY -r=2 -l=next -hf=8`
